export const testimonials = {
  top: [
    {
      id: 1,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 2,
      name: "Laura",
      title: "Mama lui Iris",
      info: " Și eu mă bucur ca merge cu drag la germană. Încă nu mi-am format o părere legat de cat de mult pricepe – acasă nu ne-a spus foarte multe, însă cunoscând-o cred ca înmagazinează informația și o să comunice când o să se simtă mai stăpână pe sine. Aș vrea să îi iau niște povești să asculte în germană însă nu știu când ar fi momentul potrivit să începem cu asta.",
      year: 2024,
    },
    {
      id: 3,
      name: "Simona",
      title: "Mama lui Filip",
      info: "Vai cat ma bucur! Intr-adevar si acasa este foarte incantat de germana si de modalitatea de invatare prin joaca. Il antreneaza si il motiveaza mult stilul acesta! Noi din pacate nu cunoastem limba germana si nu putem conversa acasa cu el, dar ma bucur ca ii place, continuam caci ii prinde bine! Culmea, cred ca ii place chiar mai mult decat limba engleza! In plus, este si el mandru ca stie din ce in ce mai multe cuvinte!",
      year: 2024,
    },
    {
      id: 4,
      name: "Stefania",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 5,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 6,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
  ],
  middle: [
    {
      id: 1,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 2,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 3,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 4,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 5,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 6,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
  ],
  bottom: [
    {
      id: 1,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 2,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 3,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 4,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 5,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
    {
      id: 6,
      name: "Irina",
      title: "Mama Amaliei și a lui Antonio",
      info: " Amalia și Antonio vin cu plăcere la cursurile tale . Le place mult predarea prin joaca. Iar faptul că Amalia a dorit să continue cursurile fără prietena ei înseamnă pentru mine înseamnă foarte mult. Iar faptul că Antonio renunță la o ședință de fotbal pe săptămână pentru cursul de germană cântărește și mai mult. Cred că știi să atragi copiii si limba germană pare mai ușoară. Eu îți mulțumesc pentru colaborarea pe care o avem de câțiva ani!",
      year: 2024,
    },
  ],
};
